# Generated by Django 5.2.5 on 2025-08-10 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_organizationinvite_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='organizationinvite',
            options={'default_permissions': (), 'verbose_name': 'Приглашение в организацию', 'verbose_name_plural': 'Приглашения в организации'},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'default_permissions': (), 'verbose_name': 'Участник организации', 'verbose_name_plural': 'Участники организаций'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'default_permissions': (), 'verbose_name': 'Участник проекта', 'verbose_name_plural': 'Участники проектов'},
        ),
        migrations.AlterModelOptions(
            name='projectpriority',
            options={'default_permissions': (), 'ordering': ['level', 'name'], 'verbose_name': 'Приоритет проекта', 'verbose_name_plural': 'Приоритеты проектов'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'default_permissions': (), 'ordering': ['order', 'name'], 'verbose_name': 'Статус проекта', 'verbose_name_plural': 'Статусы проектов'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': (), 'ordering': ['kanban_order', '-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'default_permissions': (), 'ordering': ['-uploaded_at'], 'verbose_name': 'Прикрепленный файл', 'verbose_name_plural': 'Прикрепленные файлы'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'default_permissions': (), 'ordering': ['created_at'], 'verbose_name': 'Комментарий к задаче', 'verbose_name_plural': 'Комментарии к задачам'},
        ),
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'default_permissions': (), 'ordering': ['level', 'name'], 'verbose_name': 'Приоритет задачи', 'verbose_name_plural': 'Приоритеты задач'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'default_permissions': (), 'ordering': ['order', 'name'], 'verbose_name': 'Статус задачи', 'verbose_name_plural': 'Статусы задач'},
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'default_permissions': (), 'ordering': ['-date', '-created_at'], 'verbose_name': 'Учет времени', 'verbose_name_plural': 'Учет времени'},
        ),
        migrations.AddField(
            model_name='project',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пользовательские поля'),
        ),
        migrations.AddField(
            model_name='task',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пользовательские поля'),
        ),
        migrations.CreateModel(
            name='FieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('project', 'Проект'), ('task', 'Задача')], max_length=20, verbose_name='Тип сущности')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$')], verbose_name='Системное имя')),
                ('label', models.CharField(max_length=128, verbose_name='Название поля')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('checkbox', 'Чекбокс'), ('textarea', 'Текстовая область')], max_length=20, verbose_name='Тип')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Настройка поля',
                'verbose_name_plural': 'Настройки полей',
                'ordering': ['entity_type', 'sort_index', 'id'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'name'), name='uniq_field_per_org_entity')],
            },
        ),
    ]
